"""empty message

Revision ID: 20af5a3f88ab
Revises: 
Create Date: 2025-04-12 23:45:40.094284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20af5a3f88ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('era', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_era_name'), ['name'], unique=True)

    with op.batch_alter_table('region', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_region_name'), ['name'], unique=True)

    with op.batch_alter_table('resolution', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_resolution_name'), ['name'], unique=True)

    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_video_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_name'))

    with op.batch_alter_table('resolution', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resolution_name'))
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('region', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_region_name'))
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('era', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_era_name'))
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
